---
# This is a sample database file for the DataMapper ORM
:development: &defaults
  :adapter: mysql
  :database: merbivore_blog_dev
  :username: merbivore
  :password: s3cr3ts
  :host: localhost

:test:
  <<: *defaults
  :database: merbivore_blog_test

:production:
  <<: *defaults
  :database: merbivoreblog_prod
  :host: mysql50-3-master
  :username: merbivore_db
  :password: p6Uswasw
